# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_catalog', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер в каталоге')),
                ('brand', models.CharField(max_length=120, unique=True, verbose_name='Бренд производителя')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('time_shipping', models.CharField(max_length=120, verbose_name='Время доставки')),
            ],
            options={
                'verbose_name': 'Номер в каталоге',
                'verbose_name_plural': 'Номера в каталоге',
                'ordering': ['number_catalog'],
            },
        ),
    ]
