# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_catalog',
            field=models.CharField(max_length=120, unique=True, verbose_name='Номер в каталоге'),
        ),
    ]
