# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_auto_20161211_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_detail',
            field=models.CharField(default='', max_length=120, verbose_name='Название детали'),
        ),
    ]
