# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0003_product_name_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=120, verbose_name='Бренд производителя'),
        ),
    ]
